---
title: "GEO query"
author: "Sasha Ajay Malkani"
date: "2025-10-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Installing Bioconductor

```{r 1. Installing Bioconductor}
# if (!require("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install()

```

## 2. Installing "GEOquery"

```{r 2. Installing "GEOquery"}
BiocManager::install(c("GEOquery"), force = TRUE)

```

## 3. Troubleshooting installing packages

```{r 3. Troubleshooting installing packages}
BiocManager::valid()

BiocManager::install(c(
  "BiocParallel", "promises", "Rsamtools"
), update = TRUE, ask = FALSE, force = TRUE)


```

## 4. Load Libraries

```{r 4. Load Libraries}
library(GenomicRanges)
library(GEOquery)
library(Biobase)
library(GenomicFiles)

```

## 5. Downloading data from GEO

```{r 5. Downloading data from GEO}
elist <- getGEO("GSE11675")

```

## 6. Class

```{r 6. Class}
class(elist)

```

## 7. Length of list

```{r 7. Length of list}
length(elist)

```

## 8. Name of elist

```{r 8. Name of elist}
names(elist)

```

## 9. Get the data

```{r 9. Get the data}
eData = elist[[1]]
eData

```

## 10. The names of the phenotype data

```{r 10. The names of the phenotype data}
names(pData(eData))

```

## 11. Accessing the raw (supplementary) data

```{r 11. Accessing the raw (supplementary) data}
eList2 <- getGEOSuppFiles("GSE11675")

```

## 12. Look at the downloaded tar files

```{r 12. Look at the downloaded tar files}
eList2

```

## 

```{r }


```

## 

```{r }


```

